### PR TITLE
Dream land Stage

### PR DESCRIPTION
**Pull request by Alekemon**
Kirby stage from Smash 64.

Credits for the assets goes to Mr Pinguin. The song is from Smash Melee.

### CODE REVIEW

**Comment by Alekemon** [comment]
I'm making some stages, so can you please check this?
After this, I have more stages

**Comment by Alekemon** [comment]
And the "add samus files" doesn't affect anything, that's on another branch

**Comment by Alekemon** [comment]
can you please check it out so I can pull more stages and characters?

**Comment by lufinkey** [comment]
It looks like you added a new Global.h file and Loader.cpp file to the root of the project instead of updating the existing ones. Can you fix this please?

**Comment by lufinkey** [comment]
Other than that, this one looks good

**Comment by lufinkey** [comment]
Would you be willing to add the wind effect to this stage? Mainly to differentiate it from Battlefield

**Comment by Alekemon** [comment]
Same, not gonna work on it for the moment

**Pull request closed without merging**
