### PR TITLE
Character samus

### PR DESCRIPTION
**Pull request by Alekemon**
using smash moveset + custom final smash

### CODE REVIEW

**Comment by lufinkey** [comment]
The Samus code wasn't added to `Loader.cpp`, so it needs to be added there. Otherwise she doesn't show up in the character select.
I added it myself just to playtest the character though, and she didn't seem to be affected by gravity. She just floated above the stage. I was able to walk left and right in the air
samus-float

**Comment by Alekemon** [comment]
What can cause this?

**Comment by lufinkey** [comment]
I wasn't going to spend a whole lot of time trying to debug, so I'm not sure what code you wrote to cause that I'm sorry.

**Comment by lufinkey** [comment]
Just please playtest next time before submitting so you can find these issues before I do

**Comment by Alekemon** [comment]
Ok, sure

**Comment by Alekemon** [comment]
I'll try to update Samus, the stages won't be updated though

**Comment by lufinkey** [comment]
No worries, was just wondering. If you can get Samus fully working, i'll
try to make time to push an update to cydia

**Comment by Alekemon** [comment]
could you add the green hill zone stage too? it's now fixed

**Comment by Alekemon** [comment]
already fixed samus

**Comment by lufinkey** [comment]
Sorry had a busy week! Will check this out asap

**Comment by Alekemon** [comment]
No problem

**Comment by lufinkey** [comment]
I accidentally merged this when I went to comment. Do you mind reopening this? Sorry about that>

Also sorry for the delay. Work has been really busy, I promise I'm not blowing you off

**Comment by lufinkey** [comment]
@Alekemon I got around to testing Samus today. Most of the animations didn't work, or clipped through the bottom (see attached image). The only special attack that worked was the side special attack, and it didn't match the moveset from Smash. When I tried the final smash, I got "error: animation finalsmash_change_right does not exist!"

Screenshot 2022-05-13 193019

**Comment by naha2013** [comment]
How are you getting successful builds in xcode I keep getting sdl not found.

**Comment by lufinkey** [comment]
Are you cloning the project recursively?

**Comment by naha2013** [comment]
I'm using the git address to clone directly in xcode.

**Comment by lufinkey** [comment]
You need to clone the repository recursively as it says in the readme,
otherwise you won't get the submodules

**Comment by lufinkey** [comment]
@alekemon to fix the clipping the sprites need to be lined up to have the same frame size for each frame. Like if you have 5 frames the <size of the image> divided by 5 should be the size of every frame

**Pull request merged**
