### PR TITLE
World tournament stage

### PR DESCRIPTION
**Pull request by Alekemon**
stage from dragon ball

### CODE REVIEW

**Comment by lufinkey** [comment]
Same issue with duplicate Global.h and Loader.cpp files, but it also looks like you have a compiler error:
world-tournament-error

**Comment by lufinkey** [comment]
Also where is the art from?

**Comment by Alekemon** [comment]
Art from dragon Ball GBA Game can't remember which one now

**Comment by Alekemon** [comment]
Not gonna work on this for the moment

**Pull request closed without merging**
