### PR TITLE
Corneria stage

### PR DESCRIPTION
**Pull request by Alekemon**
Home stage for Fox. Please consider adding it.

### CODE REVIEW

**Comment by Alekemon** [comment]
this time it's not a clone of anything else, it plays like Smash Melee Corneria

**Comment by lufinkey** [comment]
I'll check it out today

**Comment by Alekemon** [comment]
ok, thanks

**Comment by lufinkey** [comment]
It looks good, but you probably want to expand the boundaries of the stage. I also noticed some blank images in the stage folder. If they're not being used for anything, you can probably remove those and their platform code from the stage

Also just wondering where's the sprite from?

**Comment by lufinkey** [comment]
The AI might also perform better if you use separate stage pieces, but that's just a suggestion I don't really mind on that one

**Comment by Alekemon** [comment]
thanks

**Comment by Alekemon** [comment]
btw, the sprite is from SSF2 Sector Z adapted to Corneria and the background from Smash Ultimate

**Comment by Alekemon** [comment]
done

**Comment by Alekemon** [comment]
feel free to test it

**Comment by lufinkey** [comment]
Been pretty busy, I'll try to get to it this week

**Comment by Alekemon** [comment]
ok, thanks

**Comment by lufinkey** [comment]
It looks like you just updated the item spawn boundaries. The item boundaries are where items spawn, the borders are where players will get destroyed if they touch, and the view borders are where the camera can move. You have to expand the border and view border properties, and adjust the item spawn bounds to be above the stage. Also as a tip, if you call `showItemBoundaries(true);` in the constructor, you can get an outline of where the item bounds are. You want the box to be above the stage, so you can see it a bit easier. Just remember to remove it before you commit.

**Comment by Alekemon** [comment]
done

**Comment by lufinkey** [comment]
Ended up just making the adjustments. There's a [PR](https://github.com/Alekemon/iSSB/pull/1) out on your fork. If you merge it I'll approve here.

In the future though, I'd recommend making the item boundaries, hang points, etc visible so you can see what you're adjusting. I ended up adding a 3rd hang point by the ship's guns since there's a platform there.

**Comment by Alekemon** [comment]
thanks, I just merged it

**Pull request merged**
