### PR TITLE
Cuphead pull request is back!

### PR DESCRIPTION
**Pull request by Alekemon**
I compiled everything and it worked. I added grab animations and fixed some missing code. That's why I'm reposting it

### CODE REVIEW

**Comment by lufinkey** [comment]
I think you're missing the Cuphead character class. It like the cuphead character just spawns Fox.
Once you compile it I'd definitely recommend running it and playing him a bit, and also messing with the Cuphead attacks to make them distinct from Fox. It may work with the animations just swapped out, but the hit directions and the way the attacks act should probably be different from Fox

**Comment by Alekemon** [comment]
I'm not the spriter, so I can't do anything. A friend of mine sprited It. And I'll check later about the character class

**Comment by lufinkey** [comment]
Oh I wasn't talking about anything wrong with the sprites. I'm just saying the character is right now just fox with animations swapped out. The attack code should probably change too

**Comment by Alekemon** [comment]
What do you mean? I changed weight and hitboxes

**Comment by lufinkey** [comment]
Oh nice I didn't see that! But there's also priorities and attack delays and stuff like that. I'll definitely look at the character class once you add it! I was just trying to say the Cuphead attacks should feel unique and not just the same as Fox's, since you had mentioned you used Fox as a base. A lot of the different character attacks are similar, but I don't want him to just feel like a clone character.

It's also worth playtesting with him for a bit and tweaking the values to make it feel more unique but also balanced. Also since you mentioned the sprites, I did see that some of the sprites are a lot of the same frames for different attacks. Is your friend willing to change them up a bit and make them feel a little more different for each attack?

I'm not trying to be nitpicky I'm actually super happy someone is contributing to this! I just want the characters to be fully playtested and tweaked, and also feel generally unique. I'm open to clone characters in some cases, like Falco with Fox, but probably not in most cases.

**Comment by Alekemon** [comment]
Sprites are not willed to change, sorry. I'll try to modify the stats, so it has not Falco/Wolf feeling.

**Comment by Alekemon** [comment]
try to compile now

**Comment by Alekemon** [comment]
now Cuphead doesn't feel like Fox

**Comment by lufinkey** [comment]
I'm still getting compilation errors on the Codelite project and the Xcode project. When I fix those it still spawns Fox in the game, and when I change it to spawn Cuphead instead the game still crashes from a missing image

Please try to test this stuff before pulling in. I really appreciate the interest in the project and the willingness to make changes! But this is something I worked really hard on and I don't want to just pull in changes without them being tested, discussed, adjusted, etc. Even with the sprites, most of them look really really good! But some, like the standard and air attacks, use the same images, and that's all I was trying to point out.

You're always free to tweak and mess with this stuff! That's why I made it open source. It's just to pull it into this main repo, you have to be willing to test stuff and change stuff

**Comment by Alekemon** [comment]
I can't test it, the compile doesn't give me error but the mouse doesn't work

**Comment by Alekemon** [comment]
I was missing the toss animations lol

**Comment by Alekemon** [comment]
> I'm still getting compilation errors on the Codelite project and the Xcode project. When I fix those it still spawns Fox in the game, and when I change it to spawn Cuphead instead the game still crashes from a missing image
> 
> Please test this stuff a lot before pulling in. I really appreciate the interest in the project and the willingness to make changes! But this is something I worked really hard on and I don't want to just pull in changes without them being tested, discussed, adjusted, etc. Even with the sprites, most of them look really really good! But some, like the standard and air attacks, use the same images, and that's all I was trying to point out.
> 
> You're always free to tweak and mess with this stuff! That's why I made it open source. It's just to pull it into this main repo, you have to be willing to test stuff and change stuff

 Can't test, compile is fine, but I can't test neither with mouse nor keyboard

**Comment by lufinkey** [comment]
Ah, thanks for letting me know. I can go ahead and try to fix that now. I'll also try to add an Android studio project after that.

**Comment by Alekemon** [comment]
Thank you so much! That way I can test on mobile too

**Comment by lufinkey** [comment]
Just got the desktop build to work and also added a macOS project. Feel free to use that. The android project is a lot to add so I don't want to do that right now

**Comment by Alekemon** [comment]
I understand... Take your time

**Comment by Alekemon** [comment]
> Just got the desktop build to work and also added a macOS project. Feel free to use that. The android project is a lot to add so I don't want to do that right now

How are you going?

**Comment by lufinkey** [comment]
Do you mind keeping separate characters as separate branches/PRs like I mentioned? Just so we can focus on one character's changes at a time

**Comment by Alekemon** [comment]
ok done

**Comment by Alekemon** [comment]
but please, could you make an android studio project when you can?

I'm having nightmares on how to compile it into apk for a friend that doesn't have PC...

**Comment by lufinkey** [comment]
Thanks! And yeah I can I've just been busy. I'll try to look into it in a bit

**Comment by Alekemon** [comment]
Thanks! I asked so in the weekend because I suppose you have work to do

**Comment by Alekemon** [comment]
added the cuphead class to the project

**Comment by Alekemon** [comment]
how are you doing with the android studio project?

**Comment by lufinkey** [comment]
Like I said, it's a lot to do. I would just test with the desktop app for now.

**Comment by lufinkey** [comment]
I probably won't have it done for a bit on account of it's difficult to get working

**Comment by lufinkey** [comment]
I spent all of today on it. It should be working

**Comment by Alekemon** [comment]
yaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaay!!!!!!!!!!!!!!!!

**Comment by Alekemon** [comment]
I'll close this pull request. But I'm making a non clone Ness that I'm making

**Comment by lufinkey** [comment]
Oh, are you not finishing Cuphead?

**Comment by lufinkey** [comment]
No need to close it if it's something you're gonna come back to. Just put
it on a separate branch...

**Comment by Alekemon** [comment]
I'm letting Cuphead as a clone, have no ideas for the moveset.
It has different properties from fox though

**Comment by lufinkey** [comment]
Understood, still worth leaving progress in a branch though

**Comment by Alekemon** [comment]
can I have multiple forks?

**Comment by lufinkey** [comment]
No, but you can have branches

**Comment by Alekemon** [comment]
uh right

**Comment by Alekemon** [comment]
ok done

**Comment by lufinkey** [comment]
You'll probably wanna make that branch fresh from this repo's master, so
you don't accidentally pull in Cuphead with your ness changes

**Comment by Alekemon** [comment]
uh right

**Comment by lufinkey** [comment]
I can give the commands if you need

**Comment by lufinkey** [comment]
This command should do what you need. Tested on my repo and it worked.
`git checkout master && git pull && git checkout -b ness && git reset --hard a79842da13593606cf50775bf8a9004f63af80f3 && git remote add lufinkey https://github.com/lufinkey/iSSB && git pull lufinkey master && git push -u origin ness`

You could also make a cuphead branch off of master and update this PR to it, but that's up to you if you want

**Comment by Alekemon** [comment]
Thx

**Comment by lufinkey** [comment]
Hey I just had a chance to check out your cuphead branch but there's no images in it, they all seem to be gone

**Comment by lufinkey** [comment]
After you merge that PR I'm gonna switch this PR to merge into the feature/cuphead branch, so cuphead changes can still exist separately

**Comment by lufinkey** [comment]
@Alekemon Apologies if my frustration has disincentivized you from working on this, just been busy with a lot. Feel free to work on Ness if you still want, that's something I'd be happy with adding, and I'm definitely willing to work with you figuring out the code.

**Comment by lufinkey** [comment]
Merged this into the `feature/cuphead` branch

**Pull request merged**
